[package]
name = "turnon"
description = "Turn on devices in your network"
homepage = "https://github.com/swsnr/turnon"
repository = "https://github.com/swsnr/turnon"
license = "MPL-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
version = "0.3.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
adw = { package = "libadwaita", version = "0.7.0", features = ["v1_6"] }
gtk = { package = "gtk4", version = "0.9.2", features = ["gnome_47"] }
glib = { version = "0.20.4", features = ["log"] }
macaddr = { version = "1.0.1", default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
async-channel = "2.3.1"
log = "0.4.22"
env_logger = { version = "0.11.5", default-features = false }
env_filter = { version = "0.1.0" }
systemd-journal-logger = "2.1.1"
futures-util = { version = "0.3.31", default-features = false }
socket2 = "0.5.7"
etherparse = "0.16.0"
gettext-rs = { version = "0.7.2", features = ["gettext-system"] }

[build-dependencies]
glib-build-tools = "0.20.0"
glob = "0.3.1"

[package.metadata.release]
pre-release-commit-message = "Release {{version}}"
tag-message = "Turn On {{tag_name}}"
publish = false
verify = false
sign-tag = true
sign-commit = true

[[package.metadata.release.pre-release-replacements]]
file = "resources/de.swsnr.turnon.metainfo.xml"
search = "version=\"next\""
replace = "version=\"{{version}}\""
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "resources/de.swsnr.turnon.metainfo.xml"
search = "date=\"9999-01-01\""
replace = "date=\"{{date}}\""
exactly = 1
