[package]
name = "wakeup"
description = "Wake up things in the network"
homepage = "https://github.com/swsnr/wakeup"
repository = "https://github.com/swsnr/wakeup"
license = "MPL-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[dependencies]
adw = { package = "libadwaita", version = "0.7.0", features = ["v1_6"] }
gtk = { package = "gtk4", version = "0.9.2", features = ["gnome_47"] }
glib = { version = "0.20.4", features = ["log", "log_macros"] }
macaddr = { version = "1.0.1", default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
async-channel = "2.3.1"
log = "0.4.22"

[build-dependencies]
glib-build-tools = "0.20.0"
glob = "0.3.1"

[dev-dependencies]
socket2 = "0.5.7"
etherparse = "0.16.0"
