
# cargo-vet audits file

[audits]

[[trusted.aho-corasick]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2025-10-26"
notes = "Trusted by mozilla"

[[trusted.memchr]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2025-10-26"
notes = "Trusted by mozilla"

[[trusted.regex]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2025-10-26"
notes = "Trusted by mozilla"

[[trusted.regex-automata]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2025-10-26"
notes = "Trusted by mozilla"

[[trusted.regex-syntax]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2025-10-26"
notes = "Trusted by mozilla"
