
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.turnon]
criteria = "safe-to-run"

[[exemptions.arrayvec]]
version = "0.7.6"
criteria = "safe-to-run"

[[exemptions.async-channel]]
version = "2.3.1"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.block]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.cairo-rs]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.cairo-sys-rs]]
version = "0.20.0"
criteria = "safe-to-run"

[[exemptions.cc]]
version = "1.1.31"
criteria = "safe-to-run"

[[exemptions.cfg-expr]]
version = "0.16.0"
criteria = "safe-to-run"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.20"
criteria = "safe-to-run"

[[exemptions.env_filter]]
version = "0.1.2"
criteria = "safe-to-run"

[[exemptions.env_logger]]
version = "0.11.5"
criteria = "safe-to-run"

[[exemptions.errno]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.etherparse]]
version = "0.16.0"
criteria = "safe-to-run"

[[exemptions.event-listener]]
version = "5.3.1"
criteria = "safe-to-run"

[[exemptions.event-listener-strategy]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.field-offset]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.futures-channel]]
version = "0.3.30"
criteria = "safe-to-run"

[[exemptions.futures-executor]]
version = "0.3.30"
criteria = "safe-to-run"

[[exemptions.futures-io]]
version = "0.3.30"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf-sys]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.gdk4]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.gdk4-sys]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.gettext-rs]]
version = "0.7.2"
criteria = "safe-to-run"

[[exemptions.gettext-sys]]
version = "0.22.5"
criteria = "safe-to-run"

[[exemptions.gio]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.gio-sys]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.glib]]
version = "0.20.4"
criteria = "safe-to-run"

[[exemptions.glib-build-tools]]
version = "0.20.0"
criteria = "safe-to-run"

[[exemptions.glib-macros]]
version = "0.20.3"
criteria = "safe-to-run"

[[exemptions.glib-sys]]
version = "0.20.2"
criteria = "safe-to-run"

[[exemptions.gobject-sys]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.graphene-rs]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.graphene-sys]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.gsk4]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.gsk4-sys]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.gtk4]]
version = "0.9.2"
criteria = "safe-to-run"

[[exemptions.gtk4-macros]]
version = "0.9.1"
criteria = "safe-to-run"

[[exemptions.gtk4-sys]]
version = "0.9.0"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.libadwaita]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.libadwaita-sys]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.158"
criteria = "safe-to-run"

[[exemptions.linux-raw-sys]]
version = "0.4.14"
criteria = "safe-to-run"

[[exemptions.locale_config]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.macaddr]]
version = "1.0.1"
criteria = "safe-to-run"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-run"

[[exemptions.objc]]
version = "0.2.7"
criteria = "safe-to-run"

[[exemptions.objc-foundation]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.objc_id]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.pango]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.pango-sys]]
version = "0.20.1"
criteria = "safe-to-run"

[[exemptions.parking]]
version = "2.2.1"
criteria = "safe-to-run"

[[exemptions.pkg-config]]
version = "0.3.30"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.rustix]]
version = "0.38.37"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.18"
criteria = "safe-to-run"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-run"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-run"

[[exemptions.socket2]]
version = "0.5.7"
criteria = "safe-to-run"

[[exemptions.system-deps]]
version = "7.0.2"
criteria = "safe-to-run"

[[exemptions.systemd-journal-logger]]
version = "2.1.1"
criteria = "safe-to-run"

[[exemptions.target-lexicon]]
version = "0.12.16"
criteria = "safe-to-run"

[[exemptions.temp-dir]]
version = "0.1.14"
criteria = "safe-to-run"

[[exemptions.value-bag]]
version = "1.9.0"
criteria = "safe-to-run"

[[exemptions.version-compare]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"
