
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.swsnr]
url = "https://raw.githubusercontent.com/swsnr/rust-supply-chain/refs/heads/main/audits.toml"

[policy.turnon]
criteria = "safe-to-run"

[[exemptions.async-channel]]
version = "2.3.1"
criteria = "safe-to-run"

[[exemptions.block]]
version = "0.1.6"
criteria = "safe-to-run"
suggest = false
notes = "Only used by objc-foundation which in turn is only used on macOS by gettext-rs and thus does not apply to Turn On"

[[exemptions.cc]]
version = "1.1.31"
criteria = "safe-to-run"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.event-listener]]
version = "5.3.1"
criteria = "safe-to-run"

[[exemptions.event-listener-strategy]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.field-offset]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.gettext-rs]]
version = "0.7.2"
criteria = "safe-to-run"

[[exemptions.objc]]
version = "0.2.7"
criteria = "safe-to-run"
suggest = false
notes = "Only used by gettext-rs on macOS targets which does not apply to Turn On"

[[exemptions.objc-foundation]]
version = "0.1.1"
criteria = "safe-to-run"
suggest = false
notes = "Only used by gettext-rs on macOS targets which does not apply to Turn On"

[[exemptions.objc_id]]
version = "0.1.1"
criteria = "safe-to-run"
suggest = false
notes = "Only used by objc-foundation which in turn is only used on macOS by gettext-rs and thus does not apply to Turn On"

[[exemptions.parking]]
version = "2.2.1"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.system-deps]]
version = "7.0.2"
criteria = "safe-to-run"

[[exemptions.systemd-journal-logger]]
version = "2.1.1"
criteria = "safe-to-run"
suggest = false
notes = "Do not self-certify my own crate"

[[exemptions.temp-dir]]
version = "0.1.14"
criteria = "safe-to-run"
suggest = false
notes = "Comes in via gettext-sys, perhaps we can get rid of it, see https://github.com/gettext-rs/gettext-rs/pull/130"

[[exemptions.value-bag]]
version = "1.9.0"
criteria = "safe-to-run"

[[exemptions.version-compare]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"
suggest = false
notes = "winapi is only used by gettext-rs on Windows which does not apply to Turn On"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"
suggest = false
notes = "winapi is only used by gettext-rs on Windows which does not apply to Turn On"
