name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  metadata:
    name: Lint application metadata
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub/flatpak-builder-lint:latest
    steps:
      - uses: actions/checkout@v4
      - run: flatpak-builder-lint manifest resources/de.swsnr.turnon.metainfo.xml

  build:
    name: Build & lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: blueprint-compiler format resources/**/*.blp
        # Make the glob work
        shell: bash
      # Skip blueprint compilation because the gtk4-rs container lacks the
      # typelib files required for blueprint to resolve imports.
      - run: cargo build --all-features
        env:
          SKIP_BLUEPRINT: 1
      - run: cargo clippy --all-targets
        env:
          SKIP_BLUEPRINT: 1
      - run: cargo test
        env:
          SKIP_BLUEPRINT: 1
      - name: cargo deny check
        uses: EmbarkStudios/cargo-deny-action@v2
      - run: appstreamcli validate --explain resources/de.swsnr.turnon.metainfo.xml
